/*
Connectwise Manage Public Endpoints

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cwapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// TaxCodeInfosAPIService TaxCodeInfosAPI service
type TaxCodeInfosAPIService service

type ApiGetFinanceTaxCodesByIdInfoRequest struct {
	ctx context.Context
	ApiService *TaxCodeInfosAPIService
	id int32
	conditions *string
	childConditions *string
	customFieldConditions *string
	orderBy *string
	fields *string
	page *int32
	pageSize *int32
	pageId *int32
	clientId *string
}

// 
func (r ApiGetFinanceTaxCodesByIdInfoRequest) Conditions(conditions string) ApiGetFinanceTaxCodesByIdInfoRequest {
	r.conditions = &conditions
	return r
}

// 
func (r ApiGetFinanceTaxCodesByIdInfoRequest) ChildConditions(childConditions string) ApiGetFinanceTaxCodesByIdInfoRequest {
	r.childConditions = &childConditions
	return r
}

// 
func (r ApiGetFinanceTaxCodesByIdInfoRequest) CustomFieldConditions(customFieldConditions string) ApiGetFinanceTaxCodesByIdInfoRequest {
	r.customFieldConditions = &customFieldConditions
	return r
}

// 
func (r ApiGetFinanceTaxCodesByIdInfoRequest) OrderBy(orderBy string) ApiGetFinanceTaxCodesByIdInfoRequest {
	r.orderBy = &orderBy
	return r
}

// 
func (r ApiGetFinanceTaxCodesByIdInfoRequest) Fields(fields string) ApiGetFinanceTaxCodesByIdInfoRequest {
	r.fields = &fields
	return r
}

// 
func (r ApiGetFinanceTaxCodesByIdInfoRequest) Page(page int32) ApiGetFinanceTaxCodesByIdInfoRequest {
	r.page = &page
	return r
}

// 
func (r ApiGetFinanceTaxCodesByIdInfoRequest) PageSize(pageSize int32) ApiGetFinanceTaxCodesByIdInfoRequest {
	r.pageSize = &pageSize
	return r
}

// 
func (r ApiGetFinanceTaxCodesByIdInfoRequest) PageId(pageId int32) ApiGetFinanceTaxCodesByIdInfoRequest {
	r.pageId = &pageId
	return r
}

// 
func (r ApiGetFinanceTaxCodesByIdInfoRequest) ClientId(clientId string) ApiGetFinanceTaxCodesByIdInfoRequest {
	r.clientId = &clientId
	return r
}

func (r ApiGetFinanceTaxCodesByIdInfoRequest) Execute() (*TaxCodeInfo, *http.Response, error) {
	return r.ApiService.GetFinanceTaxCodesByIdInfoExecute(r)
}

/*
GetFinanceTaxCodesByIdInfo Get TaxCodeInfos

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id TaxCodeInfoId
 @return ApiGetFinanceTaxCodesByIdInfoRequest
*/
func (a *TaxCodeInfosAPIService) GetFinanceTaxCodesByIdInfo(ctx context.Context, id int32) ApiGetFinanceTaxCodesByIdInfoRequest {
	return ApiGetFinanceTaxCodesByIdInfoRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return TaxCodeInfo
func (a *TaxCodeInfosAPIService) GetFinanceTaxCodesByIdInfoExecute(r ApiGetFinanceTaxCodesByIdInfoRequest) (*TaxCodeInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TaxCodeInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TaxCodeInfosAPIService.GetFinanceTaxCodesByIdInfo")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/finance/taxCodes/{id}/info"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.conditions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "conditions", r.conditions, "form", "")
	}
	if r.childConditions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "childConditions", r.childConditions, "form", "")
	}
	if r.customFieldConditions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "customFieldConditions", r.customFieldConditions, "form", "")
	}
	if r.orderBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "orderBy", r.orderBy, "form", "")
	}
	if r.fields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fields", r.fields, "form", "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pageSize", r.pageSize, "form", "")
	}
	if r.pageId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pageId", r.pageId, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/vnd.connectwise.com+json; version=2025.1"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.clientId != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "clientId", r.clientId, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetFinanceTaxCodesInfoRequest struct {
	ctx context.Context
	ApiService *TaxCodeInfosAPIService
	conditions *string
	childConditions *string
	customFieldConditions *string
	orderBy *string
	fields *string
	page *int32
	pageSize *int32
	pageId *int32
	clientId *string
}

// 
func (r ApiGetFinanceTaxCodesInfoRequest) Conditions(conditions string) ApiGetFinanceTaxCodesInfoRequest {
	r.conditions = &conditions
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoRequest) ChildConditions(childConditions string) ApiGetFinanceTaxCodesInfoRequest {
	r.childConditions = &childConditions
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoRequest) CustomFieldConditions(customFieldConditions string) ApiGetFinanceTaxCodesInfoRequest {
	r.customFieldConditions = &customFieldConditions
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoRequest) OrderBy(orderBy string) ApiGetFinanceTaxCodesInfoRequest {
	r.orderBy = &orderBy
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoRequest) Fields(fields string) ApiGetFinanceTaxCodesInfoRequest {
	r.fields = &fields
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoRequest) Page(page int32) ApiGetFinanceTaxCodesInfoRequest {
	r.page = &page
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoRequest) PageSize(pageSize int32) ApiGetFinanceTaxCodesInfoRequest {
	r.pageSize = &pageSize
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoRequest) PageId(pageId int32) ApiGetFinanceTaxCodesInfoRequest {
	r.pageId = &pageId
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoRequest) ClientId(clientId string) ApiGetFinanceTaxCodesInfoRequest {
	r.clientId = &clientId
	return r
}

func (r ApiGetFinanceTaxCodesInfoRequest) Execute() ([]TaxCodeInfo, *http.Response, error) {
	return r.ApiService.GetFinanceTaxCodesInfoExecute(r)
}

/*
GetFinanceTaxCodesInfo Get List of TaxCodeInfos

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetFinanceTaxCodesInfoRequest
*/
func (a *TaxCodeInfosAPIService) GetFinanceTaxCodesInfo(ctx context.Context) ApiGetFinanceTaxCodesInfoRequest {
	return ApiGetFinanceTaxCodesInfoRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []TaxCodeInfo
func (a *TaxCodeInfosAPIService) GetFinanceTaxCodesInfoExecute(r ApiGetFinanceTaxCodesInfoRequest) ([]TaxCodeInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []TaxCodeInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TaxCodeInfosAPIService.GetFinanceTaxCodesInfo")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/finance/taxCodes/info"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.conditions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "conditions", r.conditions, "form", "")
	}
	if r.childConditions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "childConditions", r.childConditions, "form", "")
	}
	if r.customFieldConditions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "customFieldConditions", r.customFieldConditions, "form", "")
	}
	if r.orderBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "orderBy", r.orderBy, "form", "")
	}
	if r.fields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fields", r.fields, "form", "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pageSize", r.pageSize, "form", "")
	}
	if r.pageId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pageId", r.pageId, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/vnd.connectwise.com+json; version=2025.1"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.clientId != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "clientId", r.clientId, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetFinanceTaxCodesInfoCountRequest struct {
	ctx context.Context
	ApiService *TaxCodeInfosAPIService
	conditions *string
	childConditions *string
	customFieldConditions *string
	orderBy *string
	fields *string
	page *int32
	pageSize *int32
	pageId *int32
	clientId *string
}

// 
func (r ApiGetFinanceTaxCodesInfoCountRequest) Conditions(conditions string) ApiGetFinanceTaxCodesInfoCountRequest {
	r.conditions = &conditions
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoCountRequest) ChildConditions(childConditions string) ApiGetFinanceTaxCodesInfoCountRequest {
	r.childConditions = &childConditions
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoCountRequest) CustomFieldConditions(customFieldConditions string) ApiGetFinanceTaxCodesInfoCountRequest {
	r.customFieldConditions = &customFieldConditions
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoCountRequest) OrderBy(orderBy string) ApiGetFinanceTaxCodesInfoCountRequest {
	r.orderBy = &orderBy
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoCountRequest) Fields(fields string) ApiGetFinanceTaxCodesInfoCountRequest {
	r.fields = &fields
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoCountRequest) Page(page int32) ApiGetFinanceTaxCodesInfoCountRequest {
	r.page = &page
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoCountRequest) PageSize(pageSize int32) ApiGetFinanceTaxCodesInfoCountRequest {
	r.pageSize = &pageSize
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoCountRequest) PageId(pageId int32) ApiGetFinanceTaxCodesInfoCountRequest {
	r.pageId = &pageId
	return r
}

// 
func (r ApiGetFinanceTaxCodesInfoCountRequest) ClientId(clientId string) ApiGetFinanceTaxCodesInfoCountRequest {
	r.clientId = &clientId
	return r
}

func (r ApiGetFinanceTaxCodesInfoCountRequest) Execute() (*Count, *http.Response, error) {
	return r.ApiService.GetFinanceTaxCodesInfoCountExecute(r)
}

/*
GetFinanceTaxCodesInfoCount Get Count of TaxCodeInfos

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetFinanceTaxCodesInfoCountRequest
*/
func (a *TaxCodeInfosAPIService) GetFinanceTaxCodesInfoCount(ctx context.Context) ApiGetFinanceTaxCodesInfoCountRequest {
	return ApiGetFinanceTaxCodesInfoCountRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Count
func (a *TaxCodeInfosAPIService) GetFinanceTaxCodesInfoCountExecute(r ApiGetFinanceTaxCodesInfoCountRequest) (*Count, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Count
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TaxCodeInfosAPIService.GetFinanceTaxCodesInfoCount")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/finance/taxCodes/info/count"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.conditions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "conditions", r.conditions, "form", "")
	}
	if r.childConditions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "childConditions", r.childConditions, "form", "")
	}
	if r.customFieldConditions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "customFieldConditions", r.customFieldConditions, "form", "")
	}
	if r.orderBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "orderBy", r.orderBy, "form", "")
	}
	if r.fields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fields", r.fields, "form", "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pageSize", r.pageSize, "form", "")
	}
	if r.pageId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pageId", r.pageId, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/vnd.connectwise.com+json; version=2025.1"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.clientId != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "clientId", r.clientId, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
