/*
Connectwise Manage Public Endpoints

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cwapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompanyCustomNote type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyCustomNote{}

// CompanyCustomNote struct for CompanyCustomNote
type CompanyCustomNote struct {
	Id *int32 `json:"id,omitempty"`
	//  Max length: 1500;
	CustomNote string `json:"customNote"`
	Status CompanyStatusReference `json:"status"`
	Company *CompanyReference `json:"company,omitempty"`
	Info *map[string]string `json:"_info,omitempty"`
}

type _CompanyCustomNote CompanyCustomNote

// NewCompanyCustomNote instantiates a new CompanyCustomNote object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyCustomNote(customNote string, status CompanyStatusReference) *CompanyCustomNote {
	this := CompanyCustomNote{}
	this.CustomNote = customNote
	this.Status = status
	return &this
}

// NewCompanyCustomNoteWithDefaults instantiates a new CompanyCustomNote object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyCustomNoteWithDefaults() *CompanyCustomNote {
	this := CompanyCustomNote{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CompanyCustomNote) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCustomNote) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CompanyCustomNote) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CompanyCustomNote) SetId(v int32) {
	o.Id = &v
}

// GetCustomNote returns the CustomNote field value
func (o *CompanyCustomNote) GetCustomNote() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomNote
}

// GetCustomNoteOk returns a tuple with the CustomNote field value
// and a boolean to check if the value has been set.
func (o *CompanyCustomNote) GetCustomNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomNote, true
}

// SetCustomNote sets field value
func (o *CompanyCustomNote) SetCustomNote(v string) {
	o.CustomNote = v
}

// GetStatus returns the Status field value
func (o *CompanyCustomNote) GetStatus() CompanyStatusReference {
	if o == nil {
		var ret CompanyStatusReference
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CompanyCustomNote) GetStatusOk() (*CompanyStatusReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CompanyCustomNote) SetStatus(v CompanyStatusReference) {
	o.Status = v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *CompanyCustomNote) GetCompany() CompanyReference {
	if o == nil || IsNil(o.Company) {
		var ret CompanyReference
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCustomNote) GetCompanyOk() (*CompanyReference, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *CompanyCustomNote) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given CompanyReference and assigns it to the Company field.
func (o *CompanyCustomNote) SetCompany(v CompanyReference) {
	o.Company = &v
}

// GetInfo returns the Info field value if set, zero value otherwise.
func (o *CompanyCustomNote) GetInfo() map[string]string {
	if o == nil || IsNil(o.Info) {
		var ret map[string]string
		return ret
	}
	return *o.Info
}

// GetInfoOk returns a tuple with the Info field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCustomNote) GetInfoOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Info) {
		return nil, false
	}
	return o.Info, true
}

// HasInfo returns a boolean if a field has been set.
func (o *CompanyCustomNote) HasInfo() bool {
	if o != nil && !IsNil(o.Info) {
		return true
	}

	return false
}

// SetInfo gets a reference to the given map[string]string and assigns it to the Info field.
func (o *CompanyCustomNote) SetInfo(v map[string]string) {
	o.Info = &v
}

func (o CompanyCustomNote) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyCustomNote) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["customNote"] = o.CustomNote
	toSerialize["status"] = o.Status
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.Info) {
		toSerialize["_info"] = o.Info
	}
	return toSerialize, nil
}

func (o *CompanyCustomNote) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customNote",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompanyCustomNote := _CompanyCustomNote{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompanyCustomNote)

	if err != nil {
		return err
	}

	*o = CompanyCustomNote(varCompanyCustomNote)

	return err
}

type NullableCompanyCustomNote struct {
	value *CompanyCustomNote
	isSet bool
}

func (v NullableCompanyCustomNote) Get() *CompanyCustomNote {
	return v.value
}

func (v *NullableCompanyCustomNote) Set(val *CompanyCustomNote) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyCustomNote) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyCustomNote) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyCustomNote(val *CompanyCustomNote) *NullableCompanyCustomNote {
	return &NullableCompanyCustomNote{value: val, isSet: true}
}

func (v NullableCompanyCustomNote) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyCustomNote) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


